#!/usr/bin/env python3
"""Run nanopb generator with optional pkg_resources stub for environments without setuptools."""
from __future__ import absolute_import
import os
import sys

from protocol_barrel import load_message_proto_paths_relative_to_protocol_dir

script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.normpath(os.path.join(script_dir, "..", ".."))

# Prefer vendored nanopb (third_party/nanopb); else NANOPB_SRC env or legacy build path
nanopb_vendored = os.path.join(repo_root, "third_party", "nanopb")
nanopb_legacy = os.path.join(repo_root, "build", "_deps", "nanopb-src")
nanopb_src = os.environ.get("NANOPB_SRC", nanopb_vendored if os.path.isdir(nanopb_vendored) else nanopb_legacy)
generator_dir = os.path.join(nanopb_src, "generator")
proto_dir = os.path.join(nanopb_src, "generator", "proto")

# Stub pkg_resources before any nanopb imports (Python 3.12+ may not have setuptools).
class _PkgResourcesStub:
    def resource_filename(self, package, resource):
        return proto_dir

if "pkg_resources" not in sys.modules:
    sys.modules["pkg_resources"] = type(sys)("pkg_resources")
    sys.modules["pkg_resources"].resource_filename = _PkgResourcesStub().resource_filename

if not os.path.isdir(generator_dir):
    sys.stderr.write(
        "Nanopb generator not found at %s.\n"
        "Run: git submodule update --init third_party/nanopb\n" % generator_dir
    )
    sys.exit(1)

sys.path.insert(0, generator_dir)
os.chdir(repo_root)

protocol_dir = os.path.join(repo_root, "protocol")
out_dir = os.path.join(repo_root, "generated", "protocol", "c")
os.makedirs(out_dir, exist_ok=True)

# Order: host_options first; then imports from protocol/protocol.proto (see protocol_barrel.py).
_msg_proto_files = load_message_proto_paths_relative_to_protocol_dir()
NANOPB_PROTO_FILES = ["host_options.proto"] + _msg_proto_files
PROTO_INCLUDES = [rel[:-6] + ".pb.h" for rel in _msg_proto_files]


def write_protocol_aggregate_h():
    """Single include for firmware: same guard as legacy monolithic protocol.pb.h."""
    lines = [
        "/* Aggregated protocol nanopb headers (per-message .proto under protocol/messages/). "
        "Generated by run_nanopb_gen.py */",
        "#ifndef PB_PROTOCOL_PB_H_INCLUDED",
        "#define PB_PROTOCOL_PB_H_INCLUDED",
        '#include "host_options.pb.h"',
    ]
    for h in PROTO_INCLUDES:
        lines.append('#include "%s"' % h)
    lines.append("#endif /* PB_PROTOCOL_PB_H_INCLUDED */")
    path = os.path.join(out_dir, "protocol.pb.h")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def write_protocol_pb_sources_cmake():
    """protocol/CMakeLists.txt includes this; list follows protocol.proto import order."""
    lines = [
        "# Auto-generated by tools/protocol_codegen/run_nanopb_gen.py from protocol/protocol.proto.",
        "# Do not edit by hand.",
        "set(PROTOCOL_PB_C",
        '    "${PROTOCOL_GENERATED_SRC}/host_options.pb.c"',
    ]
    for rel in _msg_proto_files:
        lines.append('    "${PROTOCOL_GENERATED_SRC}/%s.pb.c"' % rel[:-6])
    lines.append(")")
    path = os.path.join(out_dir, "protocol_pb_sources.cmake")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# Invoke as module to use generator's main
import importlib.util
spec = importlib.util.spec_from_file_location("nanopb_generator", os.path.join(generator_dir, "nanopb_generator.py"))
gen = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gen)

proto_paths = [os.path.join(protocol_dir, name) for name in NANOPB_PROTO_FILES]
for p in proto_paths:
    if not os.path.isfile(p):
        sys.stderr.write("Missing proto: %s\n" % p)
        sys.exit(1)

old_argv = sys.argv
sys.argv = ["nanopb_generator", "-D", out_dir, "-I", protocol_dir, "-I", proto_dir] + proto_paths
try:
    gen.main_cli()
finally:
    sys.argv = old_argv

write_protocol_aggregate_h()
write_protocol_pb_sources_cmake()
