syntax = "proto3";

import "nanopb.proto";
import "host_options.proto";
import "messages/protocol_common.proto";

option (host.default_host_ui_module) = HOST_UI_MODULE_OTA_CONFIG;

message OtaConfigSendAddressRequest {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_REQUEST;
  uint32 target_addr = 1;
  uint32 new_address = 2;
  uint32 pan_id = 3;
}
message OtaConfigSendPositionRequest {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_REQUEST;
  uint32 target_addr = 1;
  float x = 2;
  float y = 3;
  float z = 4;
}
message OtaConfigSendTypeRequest {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_REQUEST;
  uint32 target_addr = 1;
  NodeType node_type = 2;
}
message OtaConfigSendGpioRequest {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_REQUEST;
  uint32 target_addr = 1;
  uint32 pin = 2;
  uint32 state = 3;
}
message OtaConfigSetTokenRequest {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_REQUEST;
  uint32 token = 1;
}
message OtaConfigGetTokenRequest {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_REQUEST;
}
message OtaConfigGetTokenResponse {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_RESPONSE;
  uint32 token = 1;
}
message OtaConfigGetStatsRequest {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_REQUEST;
}
message OtaConfigGetStatsResponse {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_RESPONSE;
  uint32 requests_sent = 1;
  uint32 responses_received = 2;
}

message OtaConfigUnknownMessageTypeEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 message_type = 1;
}
message OtaConfigInvalidAddressEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 address = 1;
}
message OtaConfigAddressChangedEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 old_address = 1;
  uint32 new_address = 2;
  uint32 pan_id = 3;
}
message OtaConfigPositionSetEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  float x = 1;
  float y = 2;
  float z = 3;
}
message OtaConfigInvalidNodeTypeEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  int32 node_type = 1;
}
message OtaConfigNodeTypeSetEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  int32 node_type = 1;
}
message OtaConfigInvalidGpioPinEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 pin = 1;
}
message OtaConfigInvalidGpioStateEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 state = 1;
}
message OtaConfigGpioSetEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 pin = 1;
  uint32 state = 2;
}
message OtaConfigResponseEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 src_addr = 1;
  uint32 status = 2;
  uint32 addr = 3;
  int32 type = 4;
}
message OtaConfigAuthFailedEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 src_addr = 1;
  uint32 got_token = 2;
  uint32 expected_token = 3;
}
message OtaConfigAckFromEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  string msg_name = 1 [(nanopb).max_length = 24];
  uint32 response_addr = 2;
  uint32 attempts = 3;
}
message OtaConfigNoAckFromEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  string msg_name = 1 [(nanopb).max_length = 24];
  uint32 target_addr = 2;
  uint32 attempts = 3;
}
message OtaConfigAuthTokenSetEvent {
  option (host.host_message_type) = HOST_MESSAGE_TYPE_EVENT;
  uint32 token = 1;
}
